### ISSUE TITLE
New source for list of datasets and kernels

### ISSUE THREAD

**Issue by dr-orlovsky** [pandoraboxchain/pyrrha-boxproxy#3]
Right now datasets and kernels are gathered by iterating through active cognitive jobs in
https://github.com/pandoraboxchain/pyrrha-boxproxy/blob/f2d37d9e88cb90d0485795f805611121f9fa5f54/app/function.js#L61

This leads to the fact that any kernel or dataset not used by an active cognitive job would not be found or displayed in boxchain explorer. Thus I have recently added a simple dMarket smart contract:
https://github.com/pandoraboxchain/pyrrha-consensus/blob/7ceae8290a2bd74de48fdc7e67a6ae142326632d/contracts/dmarket/PandoraMarket.sol#L7

For now, list of all registered kernels and datasets should be taken from its member array variables.

**Comment by kostysh** [comment]
done in the current version (https://github.com/pandoraboxchain/pyrrha-boxproxy/blob/4424da33067a4ec1a3d9692fb8f2e1c498c385ec/src/libs/pandora.lib.js#L565)
